version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions-dependencies:
        patterns:
          - "*"

    cooldown:
      default-days: 7
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    groups:
      root-go-dependencies:
        patterns:
          - "*"

    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
  - package-ecosystem: gomod
    directory: .sage
    schedule:
      interval: monthly
    groups:
      sage-go-dependencies:
        patterns:
          - "*"
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
