version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions-dependencies:
        patterns:
          - "*" 

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    groups:
      root-go-dependencies:
        patterns:
          - "*" 

  - package-ecosystem: gomod
    directory: .sage
    schedule:
      interval: monthly
    groups:
      sage-go-dependencies:
        patterns:
          - "*" 
