run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    - dupl # allow duplication
    - funlen # allow long functions
    - gomnd # allow some magic numbers
    - wsl # unwanted amount of whitespace
    - godox # allow TODOs
    - interfacer # deprecated by the author for having too many false positives
    - testpackage # unwanted convention
    - nestif # allow deep nesting
    - unparam # allow constant parameters
    - goerr113 # allow "dynamic" errors
    - nlreturn # don't require blank lines before returns
    - wrapcheck # don't enforce error wrapping
    - paralleltest # don't require all tests to use t.Parallel()
    - exhaustivestruct # don't require exhaustive structs
    - cyclop # don't enforce cyclomatic complexity
