package protobq

import (
	"cloud.google.com/go/bigquery"
	"google.golang.org/protobuf/proto"
)

// MessageSaver implements bigquery.ValueSaver for a proto.Message.
// The message is converted to a BigQuery row using the provided MarshalOptions.
type MessageSaver struct {
	// Options to use for marshaling the Message.
	Options MarshalOptions

	// InsertID governs the best-effort deduplication feature of
	// BigQuery streaming inserts.
	//
	// If the InsertID is empty, a random InsertID will be generated by
	// this library to facilitate deduplication.
	//
	// If the InsertID is set to the sentinel value bigquery.NoDedupeID, an InsertID
	// is not sent.
	//
	// For all other non-empty values, BigQuery will use the provided
	// value for best-effort deduplication.
	InsertID string

	// Message to save.
	Message proto.Message
}

var _ bigquery.ValueSaver = &MessageSaver{}

// Save implements bigquery.ValueSaver.
func (m *MessageSaver) Save() (map[string]bigquery.Value, string, error) {
	row, err := m.Options.Marshal(m.Message)
	if err != nil {
		return nil, "", err
	}
	return row, m.InsertID, nil
}
